# Site settings
title: Awesome Inc
description: > # this means to ignore newlines until "baseurl:"
  Awesome Inc exists to create and grow high tech startups. Awesome Inc hosts community events, leads technology education courses, and offers a shared workspace environment.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://awesomeinc.org" # the base hostname & protocol for your site
keywords: "Coding, Coworking, Entrepreneur, Software"

# Markdown settings
markdown: kramdown

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed
  sourcemap: :true

# Build settings
include:
  - _redirects
  - _headers
  

timezone: America/New_York

exclude:
  - package.json
  - README.md
  - CNAME
  # - assets/sass

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-assets
  - jekyll-redirect-from
  - jekyll-sitemap

assets:
  digest: false

collections:
  applications:
    title: Applications
    output: true
    permalink: /:name/apply
  notes:
    title: Notes
    output: true
    permalink: /:name/notes
  courses:
    title: Courses
    output: true
  tutorials:
    title: Tutorials
    output: true
    permalink: "/tutorials/:path/"
  blog:
    title: Blog
    output: true
    permalink: /blog/:title
  fellowship_portfolio:
    title: Fellowship Portfolio
    output: true
  mentors:
    title: Mentors
    output: true
  events:
    title: Events
    output: true
    permalink: /events/:title
  recurring_events:
    title: Recurring Events
    output: true
    permalink: /events/:title
  job_openings:
    title: Job Openings
    output: true
  confirmation:
    title: Confirmation
    output: true
    permalink: /confirmation/:name
    

